apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: scouter-server
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: ljhiyh/scouter-server:latest
      from:
        kind: DockerImage
        name: docker.io/ljhiyh/scouter-server:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: ${NET_TCP_LISTEN_PORT}-tcp
      port: ${NET_TCP_LISTEN_PORT}
      protocol: TCP
      targetPort: 6100
    - name: ${NET_UDP_LISTEN_PORT}-udp
      port: ${NET_UDP_LISTEN_PORT}
      protocol: UDP
      targetPort: 6101
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - env:
          - name: NET_TCP_LISTEN_PORT
            value: ${NET_TCP_LISTEN_PORT}
          - name: NET_UDP_LISTEN_PORT
            value: ${NET_UDP_LISTEN_PORT}
          image: "${APP_NAME}"
          imagePullPolicy: Always
          name: scouter-server
          ports:
          - containerPort: ${NET_TCP_LISTEN_PORT}
            protocol: TCP
          - containerPort: ${NET_UDP_LISTEN_PORT}
            protocol: UDP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
parameters:
- description: The name assigned to the application.
  displayName: Application Name
  name: APP_NAME
  value: scouter-server 
- description: Scouter TCP Port to be accssible from client
  displayName: Scouter TCP Port
  name: NET_TCP_LISTEN_PORT
  value: "6100"
- description: Scouter UDP Port to be accssible from client
  displayName: Scouter UDP Port
  name: NET_UDP_LISTEN_PORT
  value: "6101"
